export const developmentAnswers = {
  agent_name: 'Frontend Quality Guardian',
  purpose: 'pr-review',
  objective: 'Revisar pull requests del frontend y proponer correcciones pequeñas sin hacer merge automático.',
  success_criteria: 'Cada pull request recibe hallazgos priorizados, evidencia y pruebas sugeridas.',
  project_stage: 'existing',
  technologies: ['typescript', 'react', 'nextjs', 'postgresql'],
  architecture: 'modular-monolith',
  repository_provider: 'github',
  environment: 'development',
  development_setup: 'docker-compose',
  ci_cd: 'github-actions',
  security_controls: ['least-privilege', 'container-scan', 'secrets-manager'],
  capabilities: ['read-repository', 'edit-code', 'run-tests', 'review-pr'],
  autonomy: 'advisory',
  knowledge_enabled: true,
  knowledge_sources: ['repository-docs', 'source-code'],
  pr_review_enabled: true,
  pr_review_focus: ['correctness', 'security', 'tests', 'architecture'],
  agent_targets: ['huascar', 'kiro', 'portable'],
  hooks_enabled: true,
  skills_enabled: true,
};

export const productionAnswers = {
  agent_name: 'EC2 Operations Advisor',
  purpose: 'operations',
  objective: 'Diagnosticar incidentes de una API en EC2 y preparar planes de remediación reversibles.',
  success_criteria: 'Cada incidente produce evidencia, hipótesis, pasos de verificación y plan de rollback.',
  project_stage: 'existing',
  technologies: ['typescript', 'express', 'sqlite', 'redis'],
  architecture: 'microservices',
  repository_provider: 'github',
  environment: 'production',
  deployment_target: 'aws-ec2',
  container_platforms: ['docker'],
  ci_cd: 'github-actions',
  infrastructure: ['terraform', 'ansible'],
  observability: ['opentelemetry', 'cloudwatch', 'sentry'],
  security_controls: ['least-privilege', 'secrets-manager', 'sbom'],
  capabilities: ['read-repository', 'inspect-infrastructure', 'operate-production'],
  autonomy: 'assisted',
  human_approval: true,
  knowledge_enabled: true,
  knowledge_sources: ['repository-docs', 'runbooks'],
  pr_review_enabled: false,
  agent_targets: ['huascar', 'portable'],
  hooks_enabled: true,
  skills_enabled: true,
};
